# Navuryx Hyprland Theme
source = ~/.config/hypr/modules/environment.conf
source = ~/.config/hypr/modules/autostart.conf
source = ~/.config/hypr/modules/appearance.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/rules.conf
source = ~/.config/hypr/modules/keybinds.conf
source = ~/.config/hypr/navuryx-user/*.conf
